### What is a tensor?

  A tensor consists of several feature vectors of a problem, nested within an organizational structure.
  This structure may or may not have a hierarchical relationship between its dimensions. If it is hierarchical,
  it means each layer further details the characteristics of the previous one. If it is not, it is simply for stacking
  the information for access and processing.
  

In [3]:
import tensorflow as tf

tf.Tensor(42, shape=(), dtype=int32)


### Constant vetors

In [9]:
# Create a constant tensor
scalar = tf.constant(7)
scalar

# Number of dimensions
scalar.ndim

0

In [8]:
# Create a vector
vector = tf.constant([10, 10])
vector

# Number of dimensions
vector.ndim

1

In [12]:
# Create a matrix
matrix = tf.constant([
    [10,7],
    [7,10]
])
matrix

# Number of dimensions
matrix.ndim

2

In [18]:
# Create a matrix with specified type
float_matrix = tf.constant([
    [2.,3.,],
    [5.,6.,],
    [8.,9.,]
], dtype=tf.float16)

float_matrix

# Number of dimensions
float_matrix.ndim

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [5., 6.],
       [8., 9.]], dtype=float16)>

In [23]:
# Create a tensor with 3 3x3 matrices
tensor = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
     [10,11,12]],

     [[13,14,15],
     [16,17,18]]
])
tensor

# Number of dimensons
tensor.ndim

3

### Variable tensors

In [27]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [31]:
# Modifying the constant tensor ( it is not possible because it is a constant)
# unchangable_tensor[0] = 7 => TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
unchangable_tensor[0].assign(7)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [29]:
# Modifying the variable tensor ( it is not possible to reassign by indexing, ex: changable_tensor[0] = 7)
changable_tensor[0].assign(7)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>